// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcAnDuxDKrqqtVt6rGnGgeILD__tb5Vhg',
    appId: '1:622304557928:web:f2a53afc6244f10b8db4dd',
    messagingSenderId: '622304557928',
    projectId: 'income-expenses-flow',
    authDomain: 'income-expenses-flow.firebaseapp.com',
    storageBucket: 'income-expenses-flow.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQHe-QnBeXdYUhr23mIrLyFF7VLtiNRUs',
    appId: '1:622304557928:android:9d992e4fd665f8f98db4dd',
    messagingSenderId: '622304557928',
    projectId: 'income-expenses-flow',
    storageBucket: 'income-expenses-flow.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNIHul1UtdkD89qZv2Z2tNRBrrqsRHAZs',
    appId: '1:622304557928:ios:a75886303272a0dc8db4dd',
    messagingSenderId: '622304557928',
    projectId: 'income-expenses-flow',
    storageBucket: 'income-expenses-flow.appspot.com',
    iosClientId: '622304557928-o03f00c1hjtd84r9u5qtbi5egnic1skf.apps.googleusercontent.com',
    iosBundleId: 'com.example.incomeExpensesFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNIHul1UtdkD89qZv2Z2tNRBrrqsRHAZs',
    appId: '1:622304557928:ios:a75886303272a0dc8db4dd',
    messagingSenderId: '622304557928',
    projectId: 'income-expenses-flow',
    storageBucket: 'income-expenses-flow.appspot.com',
    iosClientId: '622304557928-o03f00c1hjtd84r9u5qtbi5egnic1skf.apps.googleusercontent.com',
    iosBundleId: 'com.example.incomeExpensesFlow',
  );
}
